### PR TITLE
hal: mark hal_cpuJump() function as noreturn

### PR DESCRIPTION
**Pull request by Maxez**
## Description

Changed hal_cpuJump() return type to void + marked it as 'noreturn'.

## Motivation and Context

[JIRA: PD-159](https://jira.phoenix-rtos.com/browse/PD-159)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [x] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by HBuczynski** [comment]
I think that you can remove `__attribute__((noreturn))` from ia32/hal.c. In this PR it is added in function declaration in `hal.h`.

https://github.com/phoenix-rtos/plo/blob/0157d4157e7c850b7574562bb855b5d31dda1a26/hal/ia32/cpu.c#L24

**Comment by Maxez** [comment]
> I think that you can remove `__attribute__((noreturn))` from ia32/hal.c. In this PR it is added in function declaration in `hal.h`.
> 
> https://github.com/phoenix-rtos/plo/blob/0157d4157e7c850b7574562bb855b5d31dda1a26/hal/ia32/cpu.c#L24

Fixed.

**Review by agkaminski — APPROVED** [review]
Most likely will be have to be removed should MISRA be implemented, for now LGTM

**Comment by agkaminski** [comment]
It was good before force push - we like two empty lines separations.

**Comment by HBuczynski** [comment]
> It was good before force push - we like two empty lines separations.

Functions are grouped together according to their intended use and within the group they are separated by one line. Otherwise, there are two lines.
It was done to increase the code readability.

**Comment by agkaminski** [comment]
> 
> 
> > It was good before force push - we like two empty lines separations.
> 
> Functions are grouped together according to their intended use and within the group they are separated by one line. Otherwise, there are two lines.
> It was done to increase the code readability.

"Functions should be separated with two newline characters. "

from https://phoenix-rtos.com/documentation/coding.md

**Review by agkaminski — APPROVED** [review]

**Review by HBuczynski — APPROVED** [review]

**Pull request merged**
