### PR TITLE
cmds/cmd: the use of cites has been changed

### PR DESCRIPTION
**Pull request by kemonats**
Line:
```
if (cmd_getnext(line, &p, "\n", DEFAULT_CITES, word, sizeof(word)) == NULL) {
```
allows cmdline as multiline

Line:
```
if (cmd_getnext(word, &wp, DEFAULT_BLANKS, DEFAULT_CITES, cmd, sizeof(cmd)) == NULL) {
```
allows spaces in the command

### CODE REVIEW

**Comment by HBuczynski** [comment]
I think there is no need to use `DEFAULT_CITES` at all in cmd's code. In the previous version of plo it was use in command `cmd` which no longer exists. 
Thanks for notice.
Can I ask you to remove define `DEFAULT_CITES` and argument `const char *cites` within this PR?

**Comment by kemonats** [comment]
Do you mean changing the code of the `cmd_getnext()` function?

**Comment by HBuczynski** [comment]
> Do you mean changing the code of the `cmd_getnext()` function?

Yes, I do. 
https://github.com/phoenix-rtos/plo/blob/48dcd030f671648d7037e5ada84feb2eebc00567/cmds/cmd.c#L57

**Comment by kemonats** [comment]
Done

**Comment by HBuczynski** [comment]
LGTM! Thanks

**Pull request merged**
