### PR TITLE
STM32L4: Dual bank/script FW selection in plo

### PR DESCRIPTION
**Pull request by agkaminski**
## Description

Add bank switching command and copy plo to RAM (to allow bank switching during plo execution).

To use this feature you need to have second FW in the second flash bank (along with user script) and in the preinit script do:
```
call user.plo
bankswitch
call user.plo
```

This will cause flash bank remapping and second FW boot should first FW's user scipt magic be invalid.

## Motivation and Context

To allow upgrade feature on this target

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (stm32l4).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Review by gerard5 — COMMENTED** [review]
Tested on HW (nucleo) memory bank switching works as expected, as shown in the description, although in the descriptive part of pull-request shorthand `call user.plo` was used (which does not work, by default), it should be something like `call flash0 user.plo dabaabad` just to test the example.

**Comment by agkaminski** [comment]
@gerard5 Thanks. Yeah, full call command is still needed, I wrote simplified form to convey idea

**Review by gerard5 — APPROVED** [review]
LGTM

**Review by anglov — APPROVED** [review]
Looks like it works correctly.

**Pull request merged**
